'use client';
import { useState } from 'react';
import { useDealerStore } from '@/lib/store/dealer-store';
import { useAuth } from '@/lib/auth/provider';
export default function Inventory(){
 const {inventory,products,movements,receiveStock,adjustStock,loading}=useDealerStore();const {can}=useAuth();const [search,setSearch]=useState('');const [product,setProduct]=useState('');const [qty,setQty]=useState(1);const [reference,setReference]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 async function receive(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await receiveStock(product,qty,reference);setMessage('Stock receipt saved to Supabase.');setReference('')}catch(e){setError(e instanceof Error?e.message:'Unable to save stock')}finally{setBusy(false)}}
 async function adjust(id:string,delta:number){const reason=prompt('Reason / reference for this stock adjustment:');if(!reason)return;setBusy(true);setError('');try{await adjustStock(id,'part',delta,reason)}catch(e){setError(e instanceof Error?e.message:'Adjustment failed')}finally{setBusy(false)}}
 return <div><div className="page-heading"><div><p className="eyebrow">STOCK CONTROL</p><h1>Inventory</h1><p>Actual stock receipts and movements. Product catalogue entries do not create stock.</p></div></div>{error&&<p role="alert" className="error-message">{error}</p>}{message&&<p role="status" className="success-message">{message}</p>}{can('inventory.write')&&<form onSubmit={receive} className="admin-panel billing-editor mb-6"><h2 className="font-semibold mb-5">Receive stock</h2><div className="form-grid"><label>Product<select required value={product} onChange={e=>setProduct(e.target.value)}><option value="">Choose a product</option>{products.map(p=><option value={p.id} key={p.id}>{p.brand} {p.model_name} {p.variant}</option>)}</select></label><label>Quantity<input required type="number" min="1" step="1" value={qty} onChange={e=>setQty(Number(e.target.value))}/></label><label>Purchase bill / receipt reference<input required minLength={3} value={reference} onChange={e=>setReference(e.target.value)} /></label></div><button className="primary-button" disabled={busy}>{busy?'Saving…':'Confirm stock receipt'}</button></form>}<input className="search-field" aria-label="Search stock" placeholder="Search product or SKU" value={search} onChange={e=>setSearch(e.target.value)}/><section className="admin-panel overflow-x-auto"><table className="team-table"><thead><tr><th>PRODUCT</th><th>SKU</th><th>IN STOCK</th><th>RESERVED</th><th>AVAILABLE</th><th>ADJUST</th></tr></thead><tbody>{inventory.filter(i=>`${i.itemName} ${i.skuOrCode}`.toLowerCase().includes(search.toLowerCase())).map(i=><tr key={i.id}><td>{i.itemName}</td><td>{i.skuOrCode}</td><td>{i.qtyAvailable}</td><td>{i.qtyReserved}</td><td>{i.qtyAvailable-i.qtyReserved}</td><td><button className="secondary-button" disabled={busy||!can('inventory.write')||i.qtyAvailable<=i.qtyReserved} onClick={()=>void adjust(i.id,-1)}>−1</button> <button className="secondary-button" disabled={busy||!can('inventory.write')} onClick={()=>void adjust(i.id,1)}>+1</button></td></tr>)}</tbody></table>{!loading&&!inventory.length&&<p className="empty-state">No stock received yet.</p>}</section><section className="admin-panel mt-6 overflow-x-auto"><h2 className="font-semibold mb-4">Stock movement ledger</h2><table className="team-table"><thead><tr><th>DATE</th><th>PRODUCT</th><th>CHANGE</th><th>BEFORE → AFTER</th><th>REFERENCE</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{new Date(m.created_at).toLocaleString('en-IN')}</td><td>{inventory.find(i=>i.id===m.inventory_id)?.itemName||m.inventory_id}</td><td>{m.delta>0?'+':''}{m.delta}</td><td>{m.before_qty} → {m.after_qty}</td><td>{m.reference}</td></tr>)}</tbody></table>{!movements.length&&<p className="empty-state">No stock movements recorded.</p>}</section></div>
}
