'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Plus,Printer,Pencil,ArrowRight,CreditCard,X } from 'lucide-react';
import { useDealerStore } from '@/lib/store/dealer-store';
import { useAuth } from '@/lib/auth/provider';
import { BillingDocument,money } from '@/lib/billing/types';
export function DocumentList({kind}:{kind:'quotation'|'invoice'}){
 const {documents,payments,recordPayment,loading,error:loadError}=useDealerStore();const {can}=useAuth();const [search,setSearch]=useState('');const [selected,setSelected]=useState<BillingDocument|null>(null);const [amount,setAmount]=useState('');const [method,setMethod]=useState('upi');const [reference,setReference]=useState('');const [requestId,setRequestId]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const module=kind==='invoice'?'invoices':'quotations';
 const rows=documents.filter(d=>d.kind===kind&&`${d.number} ${d.customer_snapshot.name} ${d.customer_snapshot.phone}`.toLowerCase().includes(search.toLowerCase()));
 async function pay(e:React.FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError('');try{await recordPayment(selected.id,Number(amount),method,reference,requestId);setSelected(null)}catch(e){setError(e instanceof Error?e.message:'Payment failed')}finally{setBusy(false)}}
 return <div><div className="page-heading"><div><p className="eyebrow">DOCUMENTS & BILLING</p><h1>{kind==='invoice'?'Invoices & payments':'Quotations'}</h1><p>{rows.length} saved {module}. Open a document to edit its number, items and GST.</p></div>{can(`${module}.write`)&&<Link className="primary-button" href={`/${module}/new`}><Plus size={16}/>New {kind}</Link>}</div><input className="search-field" aria-label="Search documents" placeholder="Search number, customer or phone" value={search} onChange={e=>setSearch(e.target.value)}/><div className="documents-grid">{rows.map(d=><article key={d.id} className="admin-panel"><div className="panel-heading"><div><h2>{d.number}</h2><p>{d.document_date}{d.valid_until?` · Valid until ${d.valid_until}`:''}</p></div><span className="status-active">{kind==='invoice'?(d.amount_paid>=d.total?'Paid':'Payment due'):'Quotation'}</span></div><h3 className="font-semibold text-sm">{d.customer_snapshot.name}</h3><p className="text-xs text-slate-500 mt-1">{d.customer_snapshot.phone} · {d.customer_snapshot.village}</p><div className="document-items-preview">{d.items.map((l,i)=><p key={i}>{l.name} <span>× {l.qty}</span></p>)}</div><div className="document-amount"><span>{kind==='invoice'?`Due ${money(d.total-d.amount_paid)}`:`GST ${money(d.tax_amount)}`}</span><strong>{money(d.total)}</strong></div><div className="document-actions"><Link className="secondary-button" target="_blank" rel="noopener" href={`/${module}/${d.id}/print`}><Printer size={14}/>Print / PDF</Link>{can(`${module}.write`)&&<Link className="secondary-button" href={`/${module}/${d.id}`}><Pencil size={14}/>Edit</Link>}{kind==='quotation'&&can('invoices.write')&&!documents.some(x=>x.source_quotation_id===d.id)&&<Link className="secondary-button" href={`/invoices/new?from=${d.id}`}><ArrowRight size={14}/>Create invoice</Link>}{kind==='invoice'&&can('invoices.write')&&d.total>d.amount_paid&&<button className="primary-button" onClick={()=>{setSelected(d);setAmount(String(d.total-d.amount_paid));setRequestId(crypto.randomUUID());setReference('');setError('')}}><CreditCard size={14}/>Payment</button>}</div>{kind==='invoice'&&payments.some(p=>p.invoiceId===d.id)&&<details className="mt-4 text-xs text-slate-500"><summary>Payment history</summary>{payments.filter(p=>p.invoiceId===d.id).map(p=><p key={p.id} className="py-2">{p.paidAt.slice(0,10)} · {p.method} · {money(p.amount)} · {p.referenceNo}</p>)}</details>}</article>)}</div>{!loading&&!loadError&&!rows.length&&<div className="empty-state">No {module} found. Create your first {kind} to get started.</div>}
 {selected&&<div className="modal-overlay"><form onSubmit={pay} className="admin-panel billing-editor modal-card"><div className="panel-heading"><h2>Record payment · {selected.number}</h2><button type="button" aria-label="Close payment" onClick={()=>setSelected(null)} disabled={busy}><X size={18}/></button></div>{error&&<p className="error-message" role="alert">{error}</p>}<label>Amount (₹)<input required min="0.01" max={selected.total-selected.amount_paid} step="0.01" type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Method<select value={method} onChange={e=>setMethod(e.target.value)}>{['upi','cash','bank_transfer','cheque','finance'].map(m=><option key={m}>{m}</option>)}</select></label><label>Reference<input value={reference} onChange={e=>setReference(e.target.value)}/></label><button className="primary-button" disabled={busy}>{busy?'Saving…':'Record payment'}</button></form></div>}</div>
}
