import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth;
CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,email_confirmed_at timestamptz);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
GRANT USAGE ON SCHEMA auth TO authenticated,anon;
GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated,anon;`);
const setup=readFileSync('supabase/SETUP_FRESH_PROJECT.sql','utf8').replace(/CREATE EXTENSION IF NOT EXISTS .*;/g,'');
await db.exec(setup);
const owner='00000000-0000-4000-8000-000000000001';
const staff='00000000-0000-4000-8000-000000000002';
const outsider='00000000-0000-4000-8000-000000000003';
await db.exec(`INSERT INTO auth.users VALUES ('${owner}','suryasingh4395@gmail.com',now()),('${staff}','sales@example.com',now()),('${outsider}','unknown@example.com',now());`);
const asUser=async id=>db.exec(`RESET ROLE; SET ROLE authenticated; SELECT set_config('request.jwt.claim.sub','${id}',false);`);
const scalar=async sql=>(await db.query(sql)).rows[0];
await asUser(owner);
assert.equal((await scalar('SELECT public.access_role() role')).role,'owner');
await db.query("SELECT public.admin_assign_access(' SALES@example.com ','salesperson',true)");
await assert.rejects(db.query("SELECT public.admin_assign_access('suryasingh4395@gmail.com','accountant',true)"),/own administrator/);
await asUser(staff);
assert.equal((await scalar('SELECT public.access_role() role')).role,'salesperson');
assert.equal((await scalar("SELECT public.has_permission('customers.write') allowed")).allowed,true);
assert.equal((await scalar("SELECT public.has_permission('invoices.read') allowed")).allowed,false);
await assert.rejects(db.query("SELECT public.admin_assign_access('sales@example.com','owner',true)"),/Administrator/);
await assert.rejects(db.query("UPDATE public.access_assignments SET role='owner'"),/permission denied/);
await assert.rejects(db.query("SELECT public.admin_save_permissions('salesperson',ARRAY['invoices.write','invoices.read'])"),/Administrator/);
await assert.rejects(db.query("SELECT public.fn_confirm_sale('00000000-0000-4000-8000-000000000099')"),/permission denied/);
await db.query("INSERT INTO public.customers(name,phone,village) VALUES ('Test','1234567890','Test village')");
await asUser(outsider);
assert.equal((await scalar('SELECT public.access_role() role')).role,null);
assert.equal((await db.query('SELECT * FROM public.customers')).rows.length,0);
await assert.rejects(db.query("INSERT INTO public.customers(name,phone,village) VALUES ('Hidden','123','Test')"),/row-level security/);
await asUser(owner);
await db.query("SELECT public.admin_save_permissions('salesperson',ARRAY['customers.read'])");
await assert.rejects(db.query("SELECT public.admin_save_permissions('salesperson',ARRAY['customers.write'])"),/requires view/);
await assert.rejects(db.query("SELECT public.admin_save_permissions('owner',ARRAY['customers.read'])"),/Invalid staff role/);
await asUser(staff);
assert.equal((await scalar("SELECT public.has_permission('customers.write') allowed")).allowed,false);
assert.equal((await db.query('SELECT * FROM public.customers')).rows.length,1);
await assert.rejects(db.query("INSERT INTO public.customers(name,phone,village) VALUES ('Blocked','123','Test')"),/row-level security/);
await asUser(owner);
await db.query("SELECT public.admin_assign_access('sales@example.com','salesperson',false)");
await asUser(staff);
assert.equal((await scalar('SELECT public.access_role() role')).role,null);
assert.equal((await db.query('SELECT * FROM public.customers')).rows.length,0);
await db.exec('RESET ROLE; SET ROLE anon');
await assert.rejects(db.query('SELECT public.my_access()'),/permission denied/);
await assert.rejects(db.query('SELECT * FROM public.access_assignments'),/permission denied/);
await db.exec('RESET ROLE');
assert.ok((await db.query('SELECT * FROM public.access_audit')).rows.length>=3);
await db.close();
console.log('PASS: migrations, bootstrap admin, email normalization, preassignment, RLS, denied escalation, revoked permissions, revoked accounts, audit, anonymous denial and legacy RPC lockdown.');

