import { PGlite } from '@electric-sql/pglite';
import { readFileSync,writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA auth; CREATE TABLE auth.users(id uuid PRIMARY KEY,email text,email_confirmed_at timestamptz); CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; GRANT USAGE ON SCHEMA auth TO authenticated,anon; GRANT EXECUTE ON FUNCTION auth.uid() TO authenticated,anon;`);
for(const file of ['supabase/SETUP_FRESH_PROJECT.sql','supabase/migrations/20260912_003_live_operations.sql','supabase/migrations/20260912_004_verified_products.sql'])await db.exec(readFileSync(file,'utf8').replace(/CREATE EXTENSION IF NOT EXISTS .*;/g,''));
const admin='00000000-0000-4000-8000-000000000001',sales='00000000-0000-4000-8000-000000000002',unknown='00000000-0000-4000-8000-000000000003';
await db.exec(`INSERT INTO auth.users VALUES ('${admin}','suryasingh4395@gmail.com',now()),('${sales}','sales@example.com',now()),('${unknown}','unknown@example.com',now());`);
const asUser=async id=>db.exec(`RESET ROLE; SET ROLE authenticated; SELECT set_config('request.jwt.claim.sub','${id}',false);`);
const q=async(sql,params=[]) => (await db.query(sql,params)).rows;
const save=async payload=>(await q('SELECT to_jsonb(public.app_save_document($1::jsonb)) doc',[JSON.stringify(payload)]))[0].doc;
await asUser(admin);
assert.equal((await q('SELECT * FROM public.catalog_products')).length,59);
assert.equal((await q('SELECT * FROM public.catalog_products WHERE selling_price IS NOT NULL OR gst_rate_pct IS NOT NULL')).length,0);
assert.equal((await q('SELECT * FROM public.billing_documents')).length,0);
const product=(await q("SELECT * FROM public.catalog_products WHERE model_name='OPERT13507'"))[0];
await q('SELECT public.app_product_pricing($1,10000,18,$2)',[product.id,'8507']);
await q('SELECT public.app_receive_stock($1,10,$2)',[product.id,'TEST-PURCHASE-001']);
const stock=(await q('SELECT * FROM public.inventory'))[0];
const customer=(await q("INSERT INTO public.customers(name,phone,village) VALUES ('Test customer','9999999999','Test location') RETURNING id"))[0].id;
await q("UPDATE public.business_profile SET address='Test dealership address',phone='9999999999',terms='Test terms only' WHERE id=true");
const lines=[{productId:product.id,inventoryId:stock.id,name:'Manually renamed battery',hsnCode:'8507',qty:2,unitPrice:10000,discount:1000,gstRatePct:18},{productId:null,inventoryId:null,name:'Fitting service',hsnCode:'',qty:1,unitPrice:500,discount:0,gstRatePct:5}];
const base={kind:'quotation',number:'OM/Q/0001',customerId:customer,date:'2026-09-13',validUntil:'2026-09-30',items:lines,taxMode:'cgst_sgst',notes:'Test document'};
const quote=await save(base);
assert.equal(quote.subtotal,19500);assert.equal(quote.tax_amount,3445);assert.equal(quote.total,22945);assert.equal(quote.items[0].name,'Manually renamed battery');
assert.equal((await q('SELECT qty_available FROM public.inventory'))[0].qty_available,10,'Quotations must not decrement stock');
const invoice=await save({...base,kind:'invoice',number:'OM/BILL/0001',validUntil:null,sourceQuotationId:quote.id});
assert.equal((await q('SELECT qty_available FROM public.inventory'))[0].qty_available,8);
await assert.rejects(save({...base,kind:'invoice',number:'OM/BILL/0002',sourceQuotationId:quote.id}),/duplicate key/);
assert.equal((await q('SELECT qty_available FROM public.inventory'))[0].qty_available,8,'Failed conversion must roll back stock');
await assert.rejects(save({...base,number:quote.number}),/duplicate key/);
await assert.rejects(save({...base,number:'OM/Q/NOGST',items:[{...lines[0],gstRatePct:null}]}),/Invalid item/);
await assert.rejects(save({...base,number:'OM/Q/BAD',items:[{...lines[0],discount:999999}]}),/Invalid item/);
await assert.rejects(save({...base,kind:'invoice',number:'OM/BILL/TOOMUCH',items:[{...lines[0],qty:999}]}),/Insufficient/);
const edited=await save({...base,id:invoice.id,kind:'invoice',number:'CUSTOM-BILL-9',items:[{...lines[0],qty:3},lines[1]],sourceQuotationId:quote.id,expectedUpdatedAt:invoice.updated_at});
assert.equal(edited.number,'CUSTOM-BILL-9');assert.equal((await q('SELECT qty_available FROM public.inventory'))[0].qty_available,7,'Edit applies quantity delta only');
await assert.rejects(save({...base,id:invoice.id,kind:'invoice',sourceQuotationId:quote.id,expectedUpdatedAt:invoice.updated_at}),/Document changed/);
const payId='00000000-0000-4000-8000-000000000010';
await q('SELECT public.app_record_payment($1,$2,1000,$3,$4)',[payId,invoice.id,'upi','TEST-UTR']);
await q('SELECT public.app_record_payment($1,$2,1000,$3,$4)',[payId,invoice.id,'upi','TEST-UTR']);
assert.equal((await q('SELECT * FROM public.billing_payments')).length,1,'Payment retries are idempotent');
await assert.rejects(q('SELECT public.app_record_payment($1,$2,999999,$3,$4)',['00000000-0000-4000-8000-000000000011',invoice.id,'cash','']),/exceeds/);
const paid=(await q('SELECT to_jsonb(d) doc FROM public.billing_documents d WHERE id=$1',[invoice.id]))[0].doc;
assert.equal(paid.amount_paid,1000);
await assert.rejects(save({...base,id:invoice.id,kind:'invoice',number:paid.number,sourceQuotationId:quote.id,expectedUpdatedAt:paid.updated_at,items:[{...lines[1],unitPrice:10}]}),/below payments/);
await q("SELECT public.admin_assign_access('sales@example.com','salesperson',true)");
await asUser(sales);
assert.equal((await q('SELECT * FROM public.billing_documents')).length,1,'Sales role reads quotes, not invoices');
await assert.rejects(save({...base,kind:'invoice',number:'FORBIDDEN'}),/permission required/);
await assert.rejects(q("UPDATE public.billing_documents SET total=1"),/permission denied/);
await assert.rejects(q('SELECT public.app_move_stock($1,1,$2)',[stock.id,'BYPASS']),/permission denied/);
await asUser(unknown);assert.equal((await q('SELECT * FROM public.billing_documents')).length,0);assert.equal((await q('SELECT * FROM public.catalog_products')).length,0);
await db.exec('RESET ROLE; SET ROLE anon');await assert.rejects(q('SELECT * FROM public.billing_documents'),/permission denied/);
// Saved test output is outside application imports, used only for print layout QA.
writeFileSync('tests/print-fixture.json',JSON.stringify(paid,null,2));
await db.close();console.log('PASS: 59 sourced products, empty operations, mixed GST, custom names/numbers, duplicate rejection, stock transactions and rollback, edit deltas, stale edits, payment retries/limits, and role enforcement.');
