import {notFound} from 'next/navigation';
import Link from 'next/link';
import {serverSupabase} from '@/lib/supabase/server';
import {PrintButton} from '@/components/billing/PrintButton';
import {Row,WorkshopData,label} from '@/lib/workshop/types';
export default async function JobPrint({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const db=await serverSupabase();const {data,error}=await db.rpc('ws_snapshot');if(error||!data)notFound();const d=data as WorkshopData;const job=d.jobs.find(j=>j.id===id);if(!job)notFound();const c=d.customers.find(c=>c.id===job.customer_id),v=d.vehicles.find(v=>v.id===job.vehicle_id);
 return <div className="document-frame"><div className="print-toolbar"><Link href="/service">← Workshop</Link><PrintButton/></div><article className="document-sheet"><header className="print-header"><h1>OM MOTORS</h1><div><h2>JOB CARD</h2><strong>{job.number}</strong></div></header><section className="print-customer"><div><strong>{c?.name}</strong><p>{c?.phone} · {c?.village}</p><p>{v?.model_name} {v?.variant}</p><p>Chassis: {v?.chassis_no} · Engine: {v?.engine_no||'—'}</p><p>Motor: {v?.motor_no||'—'} · Battery: {v?.battery_no||'—'}</p></div><div><p>Received: {job.received_at}</p><p>Expected: {job.expected_date||'—'}</p><p>Meter: {job.meter??'—'} {job.meter_unit}</p><p>Status: {label(job.status)}</p></div></section>{['complaint','diagnosis','findings','work_performed','notes','recommended_work'].map(k=><section key={k}><h3>{label(k)}</h3><p className="preserve-lines">{job[k]||'—'}</p></section>)}<h3>Parts used</h3><table className="print-items"><thead><tr><th>Part</th><th>Quantity</th></tr></thead><tbody>{job.parts_used.map((p:Row,i:number)=><tr key={i}><td>{d.inventory.find(s=>s.id===p.inventoryId)?.item_name||p.inventoryId}</td><td>{p.qty}</td></tr>)}</tbody></table><h3>Technicians</h3><p>{job.technician_emails.join(', ')}</p><p>Labour time: {job.labour_hours} hours</p><p>Next service: {job.next_service_date||'—'} / {job.next_service_meter||'—'} {job.meter_unit}</p><footer className="print-footer">Customer signature __________________ <span>Workshop signature __________________</span></footer></article></div>
}
