'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase/client';
import {Row} from '@/lib/workshop/types';
export function Attachments({entity,id,editable}:{entity:string;id:string;editable:boolean}){
 const [rows,setRows]=useState<Row[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[label,setLabel]=useState('');
 async function load(){const {data,error}=await supabase!.rpc('ws_attachments',{p_entity:entity,p_id:id});if(error){setError(error.message);return}setRows(await Promise.all((data||[]).map(async(r:Row)=>{const s=await supabase!.storage.from('workshop-evidence').createSignedUrl(r.object_path,300);return {...r,url:s.data?.signedUrl}})))}
 useEffect(()=>{void load()},[entity,id]);
 async function upload(file:File){setBusy(true);setError('');try{if(!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type)||file.size>10*1024*1024)throw new Error('Use a JPG, PNG, WebP or PDF under 10 MB.');if(label.trim().length<2)throw new Error('Enter a label, such as Before / brakes.');const {data:{user}}=await supabase!.auth.getUser();if(!user)throw new Error('Sign in again');const path=`${entity}/${id}/${user.id}/${crypto.randomUUID()}`;const upload=await supabase!.storage.from('workshop-evidence').upload(path,file,{contentType:file.type});if(upload.error)throw upload.error;const saved=await supabase!.rpc('ws_attach',{p_entity:entity,p_id:id,p_path:path,p_label:label});if(saved.error)throw saved.error;await load();setLabel('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="ws-section"><h3>Photos & documents</h3>{error&&<p role="alert" className="error-message">{error}</p>}<div className="ws-attachments">{rows.map(r=><a key={r.id} href={r.url} target="_blank" rel="noreferrer">{r.label}<small>{new Date(r.created_at).toLocaleString()}</small></a>)}</div>{editable&&<div className="ws-toolbar"><input aria-label="Photo or document label" placeholder="Before / after / checklist section" value={label} onChange={e=>setLabel(e.target.value)}/><label className="secondary-button">{busy?'Uploading…':'Attach photo / PDF'}<input aria-label="Attach photo or PDF" className="sr-only" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" disabled={busy} onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value=''}}/></label></div>}<p className="ws-muted">Private evidence. Links expire after five minutes; reopen this record to refresh them.</p></section>
}
