'use client';
import {useState} from 'react';
import {useAuth} from '@/lib/auth/provider';
import {Row,WorkshopData,label,today,warrantyStatus} from '@/lib/workshop/types';
import {Field,Badge} from './Fields';
import {Attachments} from './Attachments';
type Props={entity:string;initial:Row;data:WorkshopData;run:(name:string,args:Row)=>Promise<any>;done:()=>void;open:(entity:string,row:Row)=>void};
export function RecordEditor({entity,initial,data,run,done,open}:Props){
 const {can,email}=useAuth();const [row,setRow]=useState<Row>({received_date:today(),vehicle_type:'tractor',inspector_email:email,assigned_email:email,technician_email:email,status:'new',result:'pending',item_type:'vehicle',start_date:today(),items:[],checklist:{},...initial});const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const change=(k:string,v:any)=>setRow(r=>({...r,[k]:v}));const options=(rows:Row[],key:string='name')=>rows.map(r=>({value:r.id,label:r[key]||r.id}));
 const staff=data.technicians.map(t=>({value:t.email,label:t.email}));const customers=data.customers.map(c=>({value:c.id,label:`${c.name} · ${c.phone}`}));const vehicles=data.vehicles.filter(v=>!row.customer_id||v.customer_id===row.customer_id).map(v=>({value:v.id,label:`${v.model_name} · ${v.chassis_no}`}));const invoices=data.invoices.filter(b=>!b.cancelled_at&&(!row.customer_id||b.customer_id===row.customer_id)).map(b=>({value:b.id,label:b.number}));const products=data.products.map(p=>({value:p.id,label:`${p.brand} ${p.model_name} ${p.variant}`}));
 const manager=can('service.write');const permission=entity==='vehicle'?(row.intake?'pdi.write':'service.write'):entity==='template'?'service_approve.write':entity==='claim'?'warranty.write':`${entity}.write`;
 const editable=(entity==='vehicle'&&row.id?manager:can(permission))&&!(entity==='claim'&&initial.status==='closed')&&!(entity==='delivery'&&row.signed_at)&&!(entity==='pdi'&&row.id&&(!manager&&row.inspector_email!==email||['sold','delivered'].includes(data.vehicles.find(v=>v.id===row.vehicle_id)?.lifecycle)));
 const field=(name:string,type='text',opts?:{value:string;label:string}[],required=false,title?:string)=><Field key={name} name={name} title={title} type={type} options={opts} required={required} value={row} change={change} disabled={entity==='vehicle'&&!!row.id&&['customer_id','vehicle_type','purchase_invoice_id','purchase_date','manufacturer','shipment_ref','supplier_invoice','received_date','inspector_email'].includes(name)}/>;
 const vehicle=data.vehicles.find(v=>v.id===(entity==='vehicle'?row.id:row.vehicle_id));const warranty=entity==='warranty'?row:data.warranties.find(w=>w.id===row.warranty_id);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await run(`ws_save_${entity}`,{p:row});done()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <><div className="ws-detail-heading"><div><p className="eyebrow">{label(entity)}</p><h2>{row.number||row.model_name||row.product_name||row.name||`New ${label(entity)}`}</h2></div>{row.id&&<Badge value={entity==='warranty'?warrantyStatus(row):row.lifecycle||row.result||row.status||'saved'}/>}</div>{error&&<p className="error-message" role="alert">{error}</p>}
 <form onSubmit={save}><fieldset disabled={busy||!editable}><div className="ws-form-grid">
 {entity==='vehicle'&&row.id&&field('correction_reason','textarea',undefined,true,'Reason for correcting vehicle details')}
 {entity==='vehicle'&&<>{!row.intake&&field('customer_id','text',customers,true,'Vehicle owner')}<Field name="product_id" title="Catalogue model" value={row} change={(k,v)=>{const p=data.products.find(p=>p.id===v);setRow(r=>({...r,[k]:v,model_name:p?.model_name||r.model_name,variant:p?.variant||'',vehicle_type:p?.category||'tractor',manufacturer:p?.brand||''}))}} options={products} required={row.intake}/>{field('model_name','text',undefined,true)}{field('variant')}{field('vehicle_type','text',['tractor','e_rickshaw','cng_rickshaw','diesel_rickshaw'].map(v=>({value:v,label:label(v)})),true)}{['chassis_no','engine_no','motor_no','battery_no','registration_no','colour','manufacturer','location'].map(k=>field(k,'text',undefined,k==='chassis_no'))}{row.intake?<>{field('received_date','date',undefined,true,'Arrival date')}{field('shipment_ref','text',undefined,true)}{field('supplier_invoice')}{field('inspector_email','text',staff,true)}</>:<>{field('purchase_date','date')}{field('purchase_invoice_id','text',invoices)}</>}</>}
 {entity==='pdi'&&<>{!row.id&&field('vehicle_id','text',vehicles,true)}{field('inspector_email','text',staff,true)}{row.id&&<><div className="ws-wide"><h3>Inspection checklist</h3><p className="ws-muted">Mandatory items require Pass or Fail. Templates apply to new inspections.</p>{Array.isArray(row.checklist)&&row.checklist.map((item:Row,i:number)=><div className="ws-check" key={item.id}><div><small>{item.section}</small><strong>{item.label}{item.required?' *':''}</strong></div><select aria-label={`${item.section} ${item.label} result`} value={item.result||''} onChange={e=>change('checklist',row.checklist.map((x:Row,n:number)=>i===n?{...x,result:e.target.value}:x))}><option value="">Not inspected</option><option value="pass">Pass</option><option value="fail">Fail</option><option value="na" disabled={item.required}>N/A</option></select><input aria-label={`${item.section} ${item.label} notes`} placeholder="Notes / corrective work" value={item.notes||''} onChange={e=>change('checklist',row.checklist.map((x:Row,n:number)=>i===n?{...x,notes:e.target.value}:x))}/></div>)}</div>{field('result','text',['pending','passed','failed','issues'].map(s=>({value:s,label:label(s)})),true)}{field('corrective_action','textarea')}{field('responsible_email','text',staff)}</>}</>}
 {entity==='template'&&<>{field('name','text',undefined,true)}{field('vehicle_type','text',['tractor','e_rickshaw','cng_rickshaw','diesel_rickshaw'].map(s=>({value:s,label:label(s)})),true)}<div className="ws-wide">{row.items.map((x:Row,i:number)=><div key={x.id} className="ws-check"><input aria-label={`Section ${i+1}`} required value={x.section} placeholder="Section" onChange={e=>change('items',row.items.map((v:Row,n:number)=>n===i?{...v,section:e.target.value}:v))}/><input aria-label={`Check ${i+1}`} required value={x.label} placeholder="Check description" onChange={e=>change('items',row.items.map((v:Row,n:number)=>n===i?{...v,label:e.target.value}:v))}/><label><input type="checkbox" checked={x.required} onChange={e=>change('items',row.items.map((v:Row,n:number)=>n===i?{...v,required:e.target.checked}:v))}/> Mandatory</label><button type="button" onClick={()=>change('items',row.items.filter((_:Row,n:number)=>n!==i))}>Remove</button></div>)}<button className="secondary-button" type="button" onClick={()=>change('items',[...row.items,{id:crypto.randomUUID(),section:'',label:'',required:true,result:'',notes:''}])}>+ Checklist item</button></div></>}
 {entity==='warranty'&&<>{field('customer_id','text',customers,true)}{field('vehicle_id','text',vehicles)}{field('product_id','text',products)}{field('item_type','text',['vehicle','battery','part','implement'].map(s=>({value:s,label:label(s)})),true)}{field('product_name','text',undefined,true)}{field('brand')}{field('serial_no','text',undefined,true)}{field('billing_invoice_id','text',invoices)}{field('invoice_no','text',undefined,false,'External invoice reference')}{field('start_date','date',undefined,true)}{field('end_date','date',undefined,true)}{field('coverage_evidence','textarea',undefined,true,'Verified coverage reference / manufacturer terms')}</>}
 {entity==='claim'&&<>{field('warranty_id','text',data.warranties.map(w=>({value:w.id,label:`${w.product_name} · ${w.serial_no} · ${warrantyStatus(w)}`})),true)}{field('job_id','text',data.jobs.filter(j=>!warranty||j.customer_id===warranty.customer_id).map(j=>({value:j.id,label:j.number})))}{field('complaint_description','textarea',undefined,true,'Issue')}{field('diagnosis','textarea')}{field('technician_email','text',staff)}{field('status','text',['new','inspection','submitted','approved','rejected','repair','replacement','closed'].map(s=>({value:s,label:label(s)})),true)}{field('review_reason','textarea',undefined,false,'Manager review / decision reason')}{field('replacement_product_id','text',products)}{field('replacement_serial')}{field('resolution','textarea')}{field('notes','textarea')}</>}
 {entity==='delivery'&&<>{field('vehicle_id','text',vehicles,true)}{field('invoice_id','text',invoices,true)}{field('assigned_email','text',staff,true)}<div className="ws-wide">{['invoice_handed','warranty_explained','manual_given','vehicle_demonstrated'].map(k=><label className="ws-check" key={k}><span>{label(k)}</span><input type="checkbox" checked={row.checklist?.[k]||false} onChange={e=>change('checklist',{...row.checklist,[k]:e.target.checked})}/></label>)}</div>{field('notes','textarea')}{can('service_approve.write')&&field('override_reason','textarea',undefined,false,'PDI exception reason (manager authorization)')}<label className="ws-field"><span>Complete delivery</span><input type="checkbox" checked={row.finish||false} onChange={e=>change('finish',e.target.checked)}/></label><p className="ws-muted">Completion requires paid invoice, inspected vehicle and all delivery checks.</p></>}
 </div>{editable&&<div className="ws-sticky-actions"><button className="primary-button" disabled={busy}>{busy?'Saving…':`Save ${label(entity)}`}</button></div>}</fieldset></form>
 {vehicle&&<section className="ws-section"><h3>Vehicle lifecycle</h3><p>{vehicle.model_name} {vehicle.variant} · {vehicle.chassis_no}</p><p>Engine {vehicle.engine_no||'—'} · Motor {vehicle.motor_no||'—'} · Battery {vehicle.battery_no||'—'}</p><Badge value={vehicle.lifecycle}/>{data.jobs.filter(j=>j.vehicle_id===vehicle.id).map(j=><button className="ws-linked-record" key={j.id} onClick={()=>open('job',j)}>{j.number} · {j.job_type} · {label(j.status)}</button>)}{data.warranties.filter(w=>w.vehicle_id===vehicle.id).map(w=><button key={w.id} className="ws-linked-record" onClick={()=>open('warranty',w)}>{w.product_name} · {w.serial_no} · {warrantyStatus(w)}</button>)}</section>}
 {entity==='warranty'&&row.id&&<section className="ws-section"><h3>Coverage & claims</h3><p>{row.start_date} – {row.end_date} · {Math.max(0,Math.ceil((Date.parse(row.end_date)-Date.parse(row.start_date))/86400000))} days</p><p>Invoice {row.invoice_no} · {data.customers.find(c=>c.id===row.customer_id)?.name}</p><div className="ws-toolbar">{can('warranty.write')&&<button className="primary-button" onClick={()=>open('claim',{warranty_id:row.id})}>Create warranty claim</button>}{manager&&row.vehicle_id&&<button className="secondary-button" onClick={()=>open('job',{customer_id:row.customer_id,vehicle_id:row.vehicle_id,job_type:'General Service'})}>Create paid repair</button>}</div>{data.claims.filter(c=>c.warranty_id===row.id).map(c=><button key={c.id} className="ws-linked-record" onClick={()=>open('claim',c)}>{c.number} · {label(c.status)} · {c.replacement_serial&&`Replacement ${c.replacement_serial}`}</button>)}</section>}
 {row.id&&['pdi','claim'].includes(entity)&&<Attachments entity={entity} id={row.id} editable={editable}/>}
 {row.id&&<section className="ws-section"><h3>Recorded activity</h3>{data.events.filter(e=>e.record_id===row.id||(entity==='vehicle'&&e.vehicle_id===row.id)).map(e=><p key={e.id} className="ws-event"><strong>{e.action}</strong><small>{new Date(e.created_at).toLocaleString()} · {e.role} · {e.actor}</small>{e.reason}</p>)}</section>}
 </>
}
